### ISSUE TITLE
KeyError: 'dxC'

### ISSUE THREAD

**Issue by atrasvinacas57** [xgcm/xgcm#203]
Hello, I'm trying to visualize output of the LLC4320 model accessed via the ECCO data portal.  I am following the online manual for llcreader. 
Everything works until I try to convert to a lat lon grid using faces_dataset_to_latlon. I get KeyError: 'dxC' and it does not continue to create the grid. 

I'd appreciate some advise.

Thank you

Armando 
[ipynb.pdf](https://github.com/xgcm/xgcm/files/4725552/ipynb.pdf)

**Comment by rabernat** [comment]
This is technically an issue for xmitgcm, not xgcm.

The recommended way to do this is with the `type='latlon'` keyword, i.e.

```python
ds = model.get_dataset(varnames=['Eta', 'Salt', 'Theta'], k_levels=[1, 10, 40], type='latlon')
```

**Comment by atrasvinacas57** [comment]
Thank you, I tried this
ds = model.get_dataset(varnames=['Eta', 'Salt', 'Theta'], k_levels=[1, 10, 40], type='latlon')
new_ds=faces_dataset_to_latlon(ds)

but I get the same error

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/opt/anaconda3/envs/PANGEA/lib/python3.8/site-packages/xarray/core/dataset.py in _construct_dataarray(self, name)
   1163         try:
-> 1164             variable = self._variables[name]
   1165         except KeyError:

KeyError: 'dxC'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-42-05a33b775f0b> in <module>
----> 1 new_ds=faces_dataset_to_latlon(ds)

~/opt/anaconda3/envs/PANGEA/lib/python3.8/site-packages/xmitgcm/llcreader/llcmodel.py in faces_dataset_to_latlon(ds, metric_vector_pairs)
    289         data_vars[vname_v] = xr.Variable(_drop_facedim(ds[vname_v].dims), data_v, ds[vname_v].attrs)
    290     for vname_u, vname_v in metric_vector_pairs:
--> 291         data_u, data_v = _faces_to_latlon_vector(ds[vname_u].data, ds[vname_v].data, metric=True)
    292         data_vars[vname_u] = xr.Variable(_drop_facedim(ds[vname_u].dims), data_u, ds[vname_u].attrs)
    293         data_vars[vname_v] = xr.Variable(_drop_facedim(ds[vname_v].dims), data_v, ds[vname_v].attrs)

~/opt/anaconda3/envs/PANGEA/lib/python3.8/site-packages/xarray/core/dataset.py in __getitem__(self, key)
   1252 
   1253         if hashable(key):
-> 1254             return self._construct_dataarray(key)
   1255         else:
   1256             return self._copy_listed(np.asarray(key))

~/opt/anaconda3/envs/PANGEA/lib/python3.8/site-packages/xarray/core/dataset.py in _construct_dataarray(self, name)
   1164             variable = self._variables[name]
   1165         except KeyError:
-> 1166             _, name, variable = _get_virtual_variable(
   1167                 self._variables, name, self._level_coords, self.dims
   1168             )

~/opt/anaconda3/envs/PANGEA/lib/python3.8/site-packages/xarray/core/dataset.py in _get_virtual_variable(variables, key, level_vars, dim_sizes)
    165         ref_var = dim_var.to_index_variable().get_level_variable(ref_name)
    166     else:
--> 167         ref_var = variables[ref_name]
    168 
    169     if var_name is None:

KeyError: 'dxC'

**Comment by rabernat** [comment]
I cannot reproduce your error. Can you report your xmitgcm and xarray versions?

```python
import xmitgcm
print(xmitgcm.__version__)
import xarray
print(xarray.__version__)
```

for me this gives
```
0.4.1+14.ga3db4d6
0.15.1
```

**Comment by atrasvinacas57** [comment]
this is what I get

import xmitgcm
print(xmitgcm.__version__)
import xarray
print(xarray.__version__)

0.4.1
0.15.1

**Comment by rabernat** [comment]
Please try upgrading to the latest (unreleased) xmitgcm

```bash
$ pip install git+https://github.com/MITgcm/xmitgcm.git
```

I believe this bug should be fixed. (We should probably release 0.4.2 soon.)

**Comment by atrasvinacas57** [comment]
I tried upgrading and still get the same problem. Attached is the pdf of the Jupyter notebook, perhaps I should wait the release of  v 0.4.2?

[eje_llcreadv2.pdf](https://github.com/xgcm/xgcm/files/4725940/eje_llcreadv2.pdf)

**Comment by rabernat** [comment]
Are you sure you upgrade worked? Can you double check that you version of xmitgcm is `0.4.1+14.ga3db4d6` or similar? I am stumped by your problem. 

Perhaps it's a python 3.8 vs. 3.7 issue...

**Comment by rabernat** [comment]
Nope, I just tried with a local python 3.8 environment _and_ xmitgcm `0.4.1` (and xarray 0.15.2). I cannot reproduce your error.

**Comment by rabernat** [comment]
Hang on, your code worked fine. Your notebook shows this line executed fine:

```
ds = model.get_dataset(varnames=['Eta', 'Salt', 'Theta'], k_levels=[1, 10, 40],␣  →type='latlon')
print(ds)
```

```
<xarray.Dataset>
Dimensions:  (face: 13, i: 17280, i_g: 17280, j: 12960, j_g: 12960, k: 3, k_l:
3, k_p1: 3, k_u: 3, time: 10312)
Coordinates:
* k_u
* k_l
* i
* k
* time
* j_g
* j
* k_p1 *face
(k_u) int64 1 10 40
(k_l) int64 1 10 40
(i) int64 0 1 2 3 4 5 6 ... 17274 17275 17276 17277 17278 17279 (k) int64 1 10 40
(time) datetime64[ns] 2011-09-13 ... 2012-11-15T15:00:00
(j_g) int64 0 1 2 3 4 5 6 ... 12954 12955 12956 12957 12958 12959 (j) int64 0 1 2 3 4 5 6 ... 12954 12955 12956 12957 12958 12959 (k_p1) int64 1 10 40
(face)int640123456789101112
...
```

After that step, it's unnecessary to call `faces_dataset_to_latlon`. It's __already__ in lat lon form!

**Comment by atrasvinacas57** [comment]
Right! 
Ok ill try this code thanks
Armando
--
Enviado desde myMail para Android miércoles, 03 junio 2020, 02:16p. m. -06:00 de Ryan Abernathey  notifications@github.com :

**Comment by rabernat** [comment]
Hi Armando. Did you respolve this?

**Comment by atrasvinacas57** [comment]
Ryan

thank you for asking. I have succeeded in working with ECCOV4 r3 and I’m am producing some very interesting time series of the model variables for one point at the surface (entrance to the Gulf of CALIFORNIA), attached a sample plot.

But I am a bit stuck working with LLC2160 model results. This is partly my fault because I’m not familiar with work in the cloud and I’m therefore struggling with Pangeo´s binder. I could use some pointers to start working with the binder to obtain subsets of data in NetCDF format, for instance.

Thank you

Armando


Dr. Armando Trasviña Castro

=========================
Grupo de Oceanografía Tropical - Laboratorio SERVANT
CICESE Unidad La Paz 
Miraflores #334 e/Mulege y La Paz
Fracc. Bella Vista
La Paz BCS Mexico 23050
Tel +52 (612) 121 3031 x 28103
trasvi@cicese.mx 
ORCID:  http://orcid.org/0000-0002-4000-9179
Researcher ID :   J-6145-2016
=========================

**Comment by jbusecke** [comment]
Is it still true that this should be a xmitgcm issue? If so, can we close this one in favor of another?

**Comment by jbusecke** [comment]
I am closing this. If you think there is still an issue on the xgcm side, feel free to reopen.
